---
title: "ISEM 2016: Ecological Network Analysis"
author: "M.K. Lau (Harvard Forest, Harvard University)"
date:
fig_caption: yes
output: ioslides_presentation

---

# Bipartite Networks

- Community ecology's gateway to ecological networks

## Base Entitites

- *L*: number of realized links in a network
- *I*: number of lower trophic
level species (e.g. plants, prey) 
- *J*: number of higher trophic level
species (e.g. pollinators, parasitoids) 
- *m*: total number of interactions for all species 
- $a_{ij}$: number of interactions between species i from the lower and
species j from the higher trophic level, also referred as “link
weight” 
- $A_i$ ($\sum_{j=1}^J a_{ij}$): total number of interactions of
species i from the ower trophic level
- $A_j$ ($\sum_{i=1}^I a_{ij}$): total number of interactions of species j from the higher
  trophic level

## Indices (Unweighted)

- Links per Species
- Connectance
- Cluster Coefficient
- Web Asymmetry
- Number of Compartments
- Extinction Slopes
- Degree Distribution
- Mean Number of Shared Hosts
- Togetherness
- C-Score
- V-Ratio
- Nestedness

## Weighted Indices

- Modularity
- Generality
- Vulnerability
- Weighted Linkage Density
- Interaction Evenness
- Interaction Strength Asymmetry
- Niche Overlap



# Introduction to enaR

## Ecosystem Network Analysis

## Extant Software

## Getting Started

## Ecosystem Network Model

## Model Construction

## Network Data Class

## Building a Network Object

## Generate the flow matrix

## Name the nodes

## Generate the inputs

## Generate the exports

## "Pack" the model into a network object

## The model network object contents

## Model Library
## Import the model sets
## Check the first few model names
## Isolate a single model
## Check out the model
## Network Model Information

## Network Visualization
## Load data
## Set the random seed to control plot output
## Plot network data object (uses plot.network)
## Set colors to use
## Extract flow information for later use.
## Get indices of positive flows
## Set the random seed to control plot output
## Scale nodes with storage
## Add node labels
## Make rounded nodes
## Scale arrows to flow magnitude
## Lastly, remove changes to the plotting parameters

## Data Input: Reading Common Data File Formats
## WAND
## Write oyster reef model to a CSV file
## Read in oyster reef model data from NEA.m formatted CSV file
## of the information in the "oyster" data object.

## Analyzing Ecosystem Models
## Balancing for Steady-State
## Check to see if the model is balanced
## To BALANCE a model if needed
## To FORCE BALANCE a model if needed

## Structural Network Analysis

## Flow Analysis
## Output-oriented direct flow matrix
## Input-oriented integral flow matrix

## Ascendency
## Storage Analysis
## Utility Analysis
## Environ Analysis
## Control Analysis
## Mixed Trophic Impacts
## Cycle Analysis
## The individual cycles
## The disjoint nexuses

## Trophic Aggregations
## Cycle analysis output for Feeding Cycles

## Other Analyses
## Examine the structure of ns
## Set plotting parameters
## Find centrality order
## Creating a barplot
## Adding labels


## Output Orientation
## Check the current orientation
## enaFlow output in row-column
## Set the global orientation to school
## Check that it worked
## enaFlow output in column-row
## Check. Outputs should be transposed from each other.
## Now change back to the default orientation ('rc')

## Multi-Model Analyses (Batch Processing)

## Example Flow Analysis

## Connecting to Other Useful Packages
## network
## sna: Social Network Analysis
## Calculate betweenness centrality
## Get vertex names
## Exclude less central node names
## labels of most central nodes
## iGraph
## The adjacency matrix
## Creating an iGraph graph
## Betweenness centrality (calculated by iGraph and sna)
## Shortest path between any two nodes
## Average path length in the network (graph theory sense)
## Diameter of the graph
## Connectivity of the gvertex.connectivity(g)  # connectivity of a graph (group cohesion)
## Detach igraph package

## EcoNet
< write.EcoNet.R
< read.EcoNet.R
< EcoNetWeb.R

## Bipartite connection
< as.bipartite.R

## Uncertainty
< enaUncertainty.R

## enaMTI and enaUtility
< relationalChange.r
< signs.r

## new models
< Chip's
< Mouquet
< Chen


## Conclusion
## References
